default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Amazarashi@178
  host: localhost

development:
  <<: *default
  database: original_product_development

test:
  <<: *default
  database: original_product_test

production:
  <<: *default
  database: original_product_production
